name: Build DSF packages

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deployment target"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - unstable-3.5
        - stable-3.5

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install NodeJS environment
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      # Install required tools
      - name: Install dependencies
        run: sudo apt install -y dpkg-sig libxml2-utils
      
      # Import GPG key for package signing
      #- name: Configure GPG key
      #  run: |
      #    echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      #  env:
      #    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      # Build DSF
      - name: Build DSF packages
        run: |
          cd pkg
          ./build.sh --target-arch=armhf --dest-dir=./out --packages=progs --no-cleanup || true
          ./build.sh --target-arch=arm64 --dest-dir=./out --packages=progs --no-cleanup || true
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./out/*/*.deb
